env: testnet
rpc_url: https://mainnet.helius-rpc.com/?api-key=2728d54b-ce26-4696-bb4d-dc8170fcd494
ws_url: wss://mainnet.helius-rpc.com/?api-key=2728d54b-ce26-4696-bb4d-dc8170fcd494
wallet_secret_key: C:\Users\genuw\.config\solana\id_devnet_custom.json
market: SOL-PERP
heartbeat_ms: 1000
use_mock: true  # using enhanced mock client for testing strategy logic
