# Drift client configuration
# Driver selection: driftpy, swift, or hybrid (NO MOCK MODE)
driver: driftpy

# Market configuration
env: devnet
market: SOL-PERP
heartbeat_ms: 1000

# Swift Configuration
swift:
  http_url: https://swift.drift.trade
  ws_url: wss://swift.drift.trade/ws

# Wallet Configuration
wallets:
  maker_keypair_path: working_keypair.json

# RPC Configuration (for DriftPy) - Use official Solana devnet for Drift access
rpc:
  http_url: https://api.devnet.solana.com
  ws_url: wss://api.devnet.solana.com
