version: "3.9"
services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports: ["6379:6379"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana-oss
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}

  # Optional: run bots in containers (or run locally with poetry)
  # bots:
  #   build: .
  #   environment:
  #     - DRIFT_ENV=testnet
  #     - REDIS_HOST=redis
  #   depends_on: [redis, prometheus, grafana]
