services:
  redis:
    image: redis:7.2-alpine
    container_name: drift-redis
    command: ["redis-server","--appendonly","yes","--requirepass","${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis_data: {}
