cluster: ${ENV:testnet}  # testnet|devnet|mainnet
driver: ${DRIVER:driftpy}  # swift|driftpy|mock

rpc:
  http_url: ${DRIFT_HTTP_URL:https://api.mainnet-beta.solana.com}
  ws_url: ${DRIFT_WS_URL:wss://api.mainnet-beta.solana.com}

swift:
  http_url: ${SWIFT_HTTP_URL:http://localhost:8787}
  ws_url: ${SWIFT_WS_URL:ws://localhost:8787/ws}

wallets:
  maker_keypair_path: ${KEYPAIR_PATH:test_keypair.json}
  jito_keypair_path: ${JITO_KEYPAIR_PATH:/abs/path/to/jito-keypair.json}
