# v1.17.0-RC — Drift/Swift Client Config

# Environment and market settings.  These values are propagated from
# environment variables via ``os.path.expandvars`` in the client builder.
env: ${ENV}
market: ${MARKET}

# When true, the client builder will return a MockDriftClient rather than
# attempting to connect to real Drift endpoints.  Set to false in
# production and provide appropriate rpc_url/ws_url values below.
use_mock: true

# Connection endpoints for a real client.  Only used when ``use_mock``
# is set to false.  See ``libs/drift/client.py`` for details.
rpc_url: ${RPC_URL_HTTP}
ws_url: ${DRIFT_WS_URL}

# Other settings are retained for backwards compatibility but are not
# consumed by the new AsyncDriftClient implementation.  They may be
# removed in a future version.
transport:
  rpc_http: ${RPC_URL_HTTP}
  rpc_ws: ${RPC_URL_WS}
  drift_ws: ${DRIFT_WS_URL}
  swift_ws: ${SWIFT_WS_URL}
  timeouts: { connect_seconds: 10, read_seconds: 20 }
  reconnect: { max_backoff_seconds: 30, jitter: true }
keys:
  maker_keypair_path: ${KEYPAIR_PATH}
  jito_keypair_path: ${JITO_KEYPAIR_PATH}
features:
  jit: ${FEATURE_JIT}
  hedge: ${FEATURE_HEDGE}
  trend: ${FEATURE_TREND}
  obi: ${FEATURE_OBI}
  crash_v2: ${FEATURE_CRASH_V2}
risk:
  soft_drawdown_pct: ${SOFT_DD_PCT}
  trend_pause_pct: ${TREND_PAUSE_PCT}
  circuit_break_pct: ${CIRCUIT_BREAK_PCT}
metrics: { port: ${METRICS_PORT} }
logging: { level: ${LOG_LEVEL} }
