env: devnet
market: SOL-PERP
use_mock: false
driver: driftpy
rpc:
  http_url: https://devnet.helius-rpc.com/?api-key=2728d54b-ce26-4696-bb4d-dc8170fcd494
  ws_url: wss://devnet.helius-rpc.com/?api-key=2728d54b-ce26-4696-bb4d-dc8170fcd494
wallets:
  maker_keypair_path: .beta_dev_wallet.json
