# Drift client config (env-driven)
# Commit this file; it expands env vars at runtime.

cluster: devnet

# Paths and endpoints are resolved from environment
keypair_path: "${KEYPAIR_PATH}"

# Solana RPC/WS (devnet)
rpc_url: "${SOLANA_RPC_URL}"
ws_url:  "${SOLANA_WS_URL}"

# Optional Swift sidecar (if you use Swift)
swift_ws_url: "${SWIFT_WS_URL}"
