#!/usr/bin/env python3
"""
Redis Setup and Management Script for Drift Bots

This script handles Redis installation, configuration, and management
for the PythLazerSubscriber caching layer.
"""

import os
import sys
import platform
import subprocess
import time
import logging
from pathlib import Path
from typing import Optional, Dict, Any

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class RedisManager:
    """Manages Redis installation and configuration"""

    def __init__(self, install_dir: Optional[str] = None):
        self.system = platform.system().lower()
        self.install_dir = Path(install_dir or self._get_default_install_dir())
        self.redis_conf = self.install_dir / "redis.conf"
        self.redis_exe = self._get_redis_exe_path()
        self.redis_cli = self._get_redis_cli_path()

    def _get_default_install_dir(self) -> str:
        """Get default Redis installation directory"""
        if self.system == "windows":
            return str(Path.home() / ".redis")
        else:
            return "/usr/local/redis" if os.geteuid() == 0 else str(Path.home() / ".redis")

    def _get_redis_exe_path(self) -> Path:
        """Get Redis server executable path"""
        if self.system == "windows":
            return self.install_dir / "redis-server.exe"
        else:
            return self.install_dir / "bin" / "redis-server"

    def _get_redis_cli_path(self) -> Path:
        """Get Redis CLI executable path"""
        if self.system == "windows":
            return self.install_dir / "redis-cli.exe"
        else:
            return self.install_dir / "bin" / "redis-cli"

    def check_redis_installed(self) -> bool:
        """Check if Redis is installed"""
        return self.redis_exe.exists()

    def download_redis_windows(self) -> bool:
        """Download and install Redis on Windows"""
        try:
            logger.info("Downloading Redis for Windows...")

            # Use PowerShell to download Redis
            download_url = "https://github.com/microsoftarchive/redis/releases/download/win-3.2.100/Redis-x64-3.2.100.zip"
            zip_path = self.install_dir.parent / "redis.zip"

            # Create directory
            self.install_dir.parent.mkdir(parents=True, exist_ok=True)

            # Download using PowerShell
            ps_command = f"""
            Invoke-WebRequest -Uri '{download_url}' -OutFile '{zip_path}'
            Expand-Archive -Path '{zip_path}' -DestinationPath '{self.install_dir.parent}' -Force
            """

            result = subprocess.run(["powershell", "-Command", ps_command],
                                  capture_output=True, text=True)

            if result.returncode != 0:
                logger.error(f"Failed to download Redis: {result.stderr}")
                return False

            # Move files from Redis-x64-3.2.100 to redis directory
            redis_extracted = self.install_dir.parent / "Redis-x64-3.2.100"
            if redis_extracted.exists():
                import shutil
                # Create destination directory if it doesn't exist
                self.install_dir.mkdir(parents=True, exist_ok=True)
                for item in redis_extracted.iterdir():
                    shutil.move(str(item), str(self.install_dir / item.name))
                redis_extracted.rmdir()
            else:
                # Files might be directly in parent directory (fallback)
                logger.warning("Expected Redis-x64-3.2.100 directory not found, checking parent directory")
                redis_files = ["redis-server.exe", "redis-cli.exe", "redis.conf"]
                parent_files = list(self.install_dir.parent.glob("*redis*"))
                if parent_files:
                    logger.info("Moving Redis files from parent directory")
                    for file_path in parent_files:
                        if file_path.name in redis_files or file_path.suffix in [".exe", ".conf"]:
                            shutil.move(str(file_path), str(self.install_dir / file_path.name))

            # Clean up zip file
            if zip_path.exists():
                zip_path.unlink()

            logger.info("Redis downloaded and extracted successfully")
            return True

        except Exception as e:
            logger.error(f"Failed to download Redis: {e}")
            return False

    def create_redis_config(self) -> bool:
        """Create optimized Redis configuration for caching"""
        config_content = f"""
# Redis configuration optimized for Drift Pyth caching
# Generated by setup_redis.py

# Basic settings
bind 127.0.0.1
port 6379
timeout 0
tcp-keepalive 300

# Memory management
maxmemory 512mb
maxmemory-policy allkeys-lru

# Persistence (disabled for pure caching)
save ""

# Logging
loglevel notice
logfile "{self.install_dir / 'redis.log'}"

# Performance
tcp-backlog 511
databases 1

# Security (local only)
protected-mode yes
"""

        try:
            self.redis_conf.parent.mkdir(parents=True, exist_ok=True)
            with open(self.redis_conf, 'w') as f:
                f.write(config_content)
            logger.info(f"Redis configuration created at {self.redis_conf}")
            return True
        except Exception as e:
            logger.error(f"Failed to create Redis config: {e}")
            return False

    def start_redis_server(self) -> bool:
        """Start Redis server"""
        try:
            if not self.redis_conf.exists():
                logger.error("Redis config not found. Run setup first.")
                return False

            logger.info("Starting Redis server...")

            if self.system == "windows":
                # Start Redis server on Windows
                process = subprocess.Popen(
                    [str(self.redis_exe), str(self.redis_conf)],
                    creationflags=subprocess.CREATE_NEW_CONSOLE
                )
            else:
                # Start Redis server on Unix-like systems
                process = subprocess.Popen(
                    [str(self.redis_exe), str(self.redis_conf)],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL
                )

            # Wait a moment for startup
            time.sleep(2)

            # Check if it's running
            if self.test_connection():
                logger.info("Redis server started successfully")
                return True
            else:
                logger.error("Redis server failed to start")
                return False

        except Exception as e:
            logger.error(f"Failed to start Redis server: {e}")
            return False

    def stop_redis_server(self) -> bool:
        """Stop Redis server"""
        try:
            if self.system == "windows":
                # Use taskkill on Windows
                result = subprocess.run(
                    ["taskkill", "/F", "/IM", "redis-server.exe"],
                    capture_output=True, text=True
                )
            else:
                # Use pkill on Unix-like systems
                result = subprocess.run(
                    ["pkill", "redis-server"],
                    capture_output=True, text=True
                )

            logger.info("Redis server stopped")
            return True
        except Exception as e:
            logger.error(f"Failed to stop Redis server: {e}")
            return False

    def test_connection(self) -> bool:
        """Test Redis connection"""
        try:
            result = subprocess.run(
                [str(self.redis_cli), "-h", "127.0.0.1", "-p", "6379", "ping"],
                capture_output=True, text=True, timeout=5
            )
            return "PONG" in result.stdout
        except Exception:
            return False

    def setup(self) -> bool:
        """Complete Redis setup"""
        logger.info("Setting up Redis for Drift Pyth caching...")

        # Check if already installed
        if self.check_redis_installed():
            logger.info("Redis already installed")
        else:
            # Install Redis
            if self.system == "windows":
                if not self.download_redis_windows():
                    return False
            else:
                logger.error("Automatic Redis installation not supported on this platform")
                logger.info("Please install Redis manually: https://redis.io/download")
                return False

        # Create configuration
        if not self.create_redis_config():
            return False

        # Test installation
        if not self.redis_exe.exists():
            logger.error("Redis executable not found after installation")
            return False

        logger.info("Redis setup completed successfully")
        return True

def main():
    """Main setup function"""
    import argparse

    parser = argparse.ArgumentParser(description="Redis setup for Drift Pyth caching")
    parser.add_argument("--install-dir", help="Redis installation directory")
    parser.add_argument("--start", action="store_true", help="Start Redis server after setup")
    parser.add_argument("--stop", action="store_true", help="Stop Redis server")
    parser.add_argument("--test", action="store_true", help="Test Redis connection")

    args = parser.parse_args()

    manager = RedisManager(args.install_dir)

    if args.stop:
        return manager.stop_redis_server()

    if args.test:
        success = manager.test_connection()
        print(f"Redis connection: {'OK' if success else 'FAILED'}")
        return success

    # Setup Redis
    if not manager.setup():
        sys.exit(1)

    # Start if requested
    if args.start:
        if not manager.start_redis_server():
            sys.exit(1)

    print("Redis setup completed successfully!")
    print(f"Redis executable: {manager.redis_exe}")
    print(f"Redis config: {manager.redis_conf}")
    print("Use --start to start the server, or run manually with:")
    print(f'"{manager.redis_exe}" "{manager.redis_conf}"')

if __name__ == "__main__":
    main()
